config/routes.rb
JavalancheScores::Application.routes.draw do
  match 'high_scores/add_new'
  match 'high_scores/top_ten'
  resources :high_scores

end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  # GET /high_scores
  # GET /high_scores.xml
  def index
    @high_scores = HighScore.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @high_scores }
    end
  end

  # GET /high_scores/1
  # GET /high_scores/1.xml
  def show
    @high_score = HighScore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @high_score }
    end
  end

  # GET /high_scores/new
  # GET /high_scores/new.xml
  def new
    @high_score = HighScore.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @high_score }
    end
  end

  # GET /high_scores/1/edit
  def edit
    @high_score = HighScore.find(params[:id])
  end

  # POST /high_scores
  # POST /high_scores.xml
  def create
    @high_score = HighScore.new(params[:high_score])

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to(@high_score, :notice => 'High score was successfully created.') }
        format.xml  { render :xml => @high_score, :status => :created, :location => @high_score }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @high_score.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /high_scores/1
  # PUT /high_scores/1.xml
  def update
    @high_score = HighScore.find(params[:id])

    respond_to do |format|
      if @high_score.update_attributes(params[:high_score])
        format.html { redirect_to(@high_score, :notice => 'High score was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @high_score.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.xml
  def destroy
    @high_score = HighScore.find(params[:id])
    @high_score.destroy

    respond_to do |format|
      format.html { redirect_to(high_scores_url) }
      format.xml  { head :ok }
    end
  end
  
  # Get Add New Score from Game
  def add_new
   
    puts "Adding New High Score"
    puts "Name:    " + params[:name]
    puts "Comment: " + params[:comment]
    puts "Score:   " + params[:score]
    
    @new_score = HighScore.new()
    @new_score.name = params[:name]
    @new_score.comment = params[:comment]
    @new_score.score = params[:score]
    currentDate = Time.new
    @new_score.date = currentDate.strftime( "%Y-%m-%d" )
    
    @new_score.save
    
    respond_to do |format|
      format.html { redirect_to(high_scores_url) }
      format.xml  { head :ok }
    end
  end
  
  # Get the Top Ten High Scores
  def top_ten
  	@high_scores_top = HighScore.find( :all, :limit=>10, :order=>"score DESC" )
  	
  	@high_scores_top.each do |score|
  		puts score.score
  	end
  	
    #respond_to do |format|
    #  format.html { redirect_to(high_scores_url) }
    #  format.xml  { head :ok }
    #end  
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/views/high_scores/_form.html.erb
<%= form_for(@high_score) do |f| %>
  <% if @high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% @high_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/high_scores/edit.html.erb
<h1>Editing high_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<h1>Listing high_scores</h1>

<table>
  <tr>
    <th>Score</th>
    <th>Name</th>
    <th>Comment</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @high_scores.each do |high_score| %>
  <tr>
    <td><%= high_score.score %></td>
    <td><%= high_score.name %></td>
    <td><%= high_score.comment %></td>
    <td><%= high_score.date %></td>
    <td><%= link_to 'Show', high_score %></td>
    <td><%= link_to 'Edit', edit_high_score_path(high_score) %></td>
    <td><%= link_to 'Destroy', high_score, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New High score', new_high_score_path %>

app/views/high_scores/new.html.erb
<h1>New high_score</h1>

<%= render 'form' %>

<%= link_to 'Back', high_scores_path %>

app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Score:</b>
  <%= @high_score.score %>
</p>

<p>
  <b>Name:</b>
  <%= @high_score.name %>
</p>

<p>
  <b>Comment:</b>
  <%= @high_score.comment %>
</p>

<p>
  <b>Date:</b>
  <%= @high_score.date %>
</p>


<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/top_ten.html.erb
<table>

<% @high_scores_top.each do |high_score| %>
  <tr>
    <td><%= high_score.score %></td>
    <td><%= high_score.name %></td>
  </tr>
<% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JavalancheScores</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>